apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv
  namespace: sample-domain3-ns
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    path: /mnt/mysql-pool/
    server: ipgoeshere