apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv
  namespace: sample-domain3-ns
spec:
  storageClassName: vsphere-storage
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/Users/rbajaj/mysqlpoddata"