apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv-ns2
  namespace: sample-domain2-ns
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/Users/rbajaj/mysqlpoddata"